### PR TITLE
Correct polymorphic function example

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by gujun720** [comment]
Thanks for your contribution. We will review and merge PRs in a timely manner going forward :)

**Comment by ShalokShalom** [comment]
Oh, I considered this project dead, is it actively worked on again?
And will this stay the case?

**Comment by gujun720** [comment]
Hi ShalokShalom, 

The Hamler project was quiet for a while, and the project team was really busy with something else. But we have never abandoned the Hamler project, the flame in the chest of Erlang programmers is still burning. ;)

We'll be reactivating the Hamler project in the next few months. In the meantime, we'd like to hear your opinion and suggestions. What do you think about the value point of projects like Hamler?

Thanks.

**Comment by ShalokShalom** [comment]
I would appreciate if you announce the next hiatus. 
Just saying nothing seems like you abandoned the project. 
Putting it on a halt, could simply be announced by a blog post.

**Pull request merged**
